version: "3.8"

services:
  postgres:
    image: pgvector/pgvector:0.8.1-pg18-trixie
    container_name: rag_postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: test_db_user
      POSTGRES_PASSWORD: test_db_password
      POSTGRES_DB: test_db
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
